### ISSUE TITLE
Error on downloading package timekit

### ISSUE THREAD

**Issue by kroliczek94** [business-science/timekit#2]
Hi, 

yesterday I tried to download package timekit into my R environment.
Unfortunately there was an error on command : install.packages("timekit").
This is error text from R console: https://pastebin.com/raw/0rPffvzF

Has anyone similar problem or any idea how to fix this problem?

**Comment by mdancho84** [comment]
Hello @kroliczek94:
I believe this is something local to your machine. I recommend to try restarting R and retry the download. 
Thanks, Matt

**Comment by mdancho84** [comment]
I'm closing.  Let me know if we need to reopen.
