### ISSUE TITLE
week.iso and year.iso

### ISSUE THREAD

**Issue by davidgohel** [business-science/timekit#4]
Hello,

Thanks for the `timekit` package. This is really usefull.

I need to aggregate TS on a weekly basis - I would like to use `week.iso` but also `year.iso`. Below a simple R script to explain my problem:

```
library(dplyr)
library(timekit)
tk_get_timeseries_signature(as.Date(c("2014-12-28", "2014-12-29", 
    "2014-12-30", "2014-12-31"))) %>% 
  as.data.frame()
```

```
       index  index.num  diff year half quarter month month.xts month.lbl day hour minute second hour12
1 2014-12-28 1419724800    NA 2014    2       4    12        11  December  28    0      0      0      0
2 2014-12-29 1419811200 86400 2014    2       4    12        11  December  29    0      0      0      0
3 2014-12-30 1419897600 86400 2014    2       4    12        11  December  30    0      0      0      0
4 2014-12-31 1419984000 86400 2014    2       4    12        11  December  31    0      0      0      0
  am.pm wday wday.xts  wday.lbl mday qday yday mweek week week.iso week2 week3 week4 mday7
1     1    1        0    Sunday   28   89  362     4   52       52     0     1     0     5
2     1    2        1    Monday   29   90  363     5   52        1     0     1     0     5
3     1    3        2   Tuesday   30   91  364     5   52        1     0     1     0     5
4     1    4        3 Wednesday   31   92  365     5   53        1     1     2     1     5
```

Aggregating with `week.iso` and `year` as grouping variables will not work as 2014-12-31 is in week 1 of year 2015.

Is there a way to get a *year.iso* variable?

**Comment by mdancho84** [comment]
Thanks for the kind words.

If I understand correctly, the `year.iso` should reflect the `week.iso`. For example, week.iso = 1 in your example should have year = 2015. Is this what you would expect?

**Comment by davidgohel** [comment]
Yes, exactly. I think that's `isoyear` in lubridate.

David

**Comment by mdancho84** [comment]
That's great if lubridate already has it. I will check and look to add shortly. Stay tuned.

**Comment by mdancho84** [comment]
I just updated the time series signature. Take a look at it and make sure it's returning the ISO year as you would expect.

**Comment by davidgohel** [comment]
I've just tested, it's perfect, thanks.
